
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'declarationDOT FLOWERCLOSE FLOWEROPEN FOR IDENTIFIER IN NUMBER\n    declaration : FOR IDENTIFIER IN NUMBER DOT NUMBER FLOWEROPEN FLOWERCLOSE\n                | FOR IDENTIFIER IN IDENTIFIER FLOWEROPEN FLOWERCLOSE\n                \n                \n    '
    
_lr_action_items = {'FOR':([0,],[2,]),'$end':([1,9,12,],[0,-2,-1,]),'IDENTIFIER':([2,4,],[3,5,]),'IN':([3,],[4,]),'NUMBER':([4,8,],[6,10,]),'FLOWEROPEN':([5,10,],[7,11,]),'DOT':([6,],[8,]),'FLOWERCLOSE':([7,11,],[9,12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'declaration':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> declaration","S'",1,None,None,None),
  ('declaration -> FOR IDENTIFIER IN NUMBER DOT NUMBER FLOWEROPEN FLOWERCLOSE','declaration',8,'p_declaration','forrustyac.py',9),
  ('declaration -> FOR IDENTIFIER IN IDENTIFIER FLOWEROPEN FLOWERCLOSE','declaration',6,'p_declaration','forrustyac.py',10),
]
